# Generated by Django 5.1.6 on 2025-11-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=300)),
                ('post_code', models.CharField(max_length=50)),
                ('no_of_beds', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=10000)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeway_property_ltd.flat')),
            ],
        ),
    ]
