# Generated by Django 5.1.6 on 2025-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeway_property_ltd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='flat',
            name='no_of_beds',
        ),
        migrations.AddField(
            model_name='flat',
            name='double_beds',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='flat',
            name='kingsize_beds',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='flat',
            name='sofa_beds',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
