# Generated by Django 5.1.6 on 2025-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeway_property_ltd', '0002_cleaners_remove_flat_no_of_beds_flat_double_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='photo_url',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
