# Generated by Django 5.1.6 on 2025-11-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeway_property_ltd', '0003_flat_photo_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cleaners',
            new_name='Cleaner',
        ),
    ]
