# Generated by Django 5.1.6 on 2025-11-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeway_property_ltd', '0004_rename_cleaners_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_notes',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
