# Generated by Django 5.1.4 on 2025-03-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=50)),
            ],
        ),
    ]
