# Generated by Django 5.1.4 on 2025-03-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_presstimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='presstimes',
            name='at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presstimes',
            name='times',
            field=models.IntegerField(null=True),
        ),
    ]
