# Generated by Django 5.1.4 on 2025-03-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_presstimes_at_alter_presstimes_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presstimes',
            old_name='at',
            new_name='was_at',
        ),
    ]
