# Generated by Django 5.1.6 on 2025-03-29 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_at_presstimes_was_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presstimes',
            name='was_at',
        ),
    ]
