# Generated by Django 5.1.4 on 2025-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_presstimes_was_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcherNBlackbird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(max_length=200)),
                ('was_at', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
