# Generated by Django 5.1.4 on 2025-03-24 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('resim', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Yil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yarismaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('juri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_ses_turkiye.juri')),
            ],
        ),
        migrations.AddField(
            model_name='juri',
            name='yil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_ses_turkiye.yil'),
        ),
    ]
