# Generated by Django 5.1.6 on 2025-03-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o_ses_turkiye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juri',
            name='resim',
            field=models.CharField(default='', max_length=500),
        ),
    ]
